//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenic.BadgeApplication.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ActivitySubmissions = new HashSet<ActivitySubmission>();
            this.ActivitySubmissions1 = new HashSet<ActivitySubmission>();
            this.BadgeAwards = new HashSet<BadgeAward>();
            this.BadgeAwards1 = new HashSet<BadgeAward>();
            this.Employee1 = new HashSet<Employee>();
            this.Employee11 = new HashSet<Employee>();
            this.EmployeePermissions = new HashSet<EmployeePermission>();
            this.Badges = new HashSet<Badge>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ADName { get; set; }
        public System.DateTime EmploymentStartDate { get; set; }
        public Nullable<System.DateTime> EmploymentEndDate { get; set; }
        public Nullable<System.DateTime> EmploymentStartDate2 { get; set; }
        public Nullable<System.DateTime> EmploymentEndDate2 { get; set; }
        public int ApprovingManagerId1 { get; set; }
        public Nullable<int> ApprovingManagerId2 { get; set; }
        public Nullable<int> AwardPayoutThreshhold { get; set; }
    
        public virtual ICollection<ActivitySubmission> ActivitySubmissions { get; set; }
        public virtual ICollection<ActivitySubmission> ActivitySubmissions1 { get; set; }
        public virtual ICollection<BadgeAward> BadgeAwards { get; set; }
        public virtual ICollection<BadgeAward> BadgeAwards1 { get; set; }
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ICollection<Employee> Employee11 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual ICollection<EmployeePermission> EmployeePermissions { get; set; }
        public virtual ICollection<Badge> Badges { get; set; }
    }
}
