//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenic.BadgeApplication.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueItemToPublish
    {
        public int QueueItemId { get; set; }
        public int BadgeAwardId { get; set; }
        public System.DateTime QueueItemCreated { get; set; }
        public int BadgeId { get; set; }
        public string BadgeName { get; set; }
        public string BadgePath { get; set; }
        public string BadgeDescription { get; set; }
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string BadgeTagline { get; set; }
        public string ADName { get; set; }
    }
}
