//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenic.BadgeApplication.DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueItem
    {
        public QueueItem()
        {
            this.QueueEventLogs = new HashSet<QueueEventLog>();
        }
    
        public int QueueItemId { get; set; }
        public int BadgeAwardId { get; set; }
        public System.DateTime QueueItemCreated { get; set; }
    
        public virtual BadgeAward BadgeAward { get; set; }
        public virtual ICollection<QueueEventLog> QueueEventLogs { get; set; }
    }
}
