// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4Mvc;
namespace Magenic.BadgeApplication.Controllers
{
    public partial class PointsReportController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PointsReportController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PointsReportController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> BadgeAwards()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BadgeAwards);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> UpdateBadgeAwards()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateBadgeAwards);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PointsReportController Actions { get { return Mvc.PointsReport; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PointsReport";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PointsReport";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string BadgeAwards = "BadgeAwards";
            public readonly string UpdateBadgeAwards = "UpdateBadgeAwards";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string BadgeAwards = "BadgeAwards";
            public const string UpdateBadgeAwards = "UpdateBadgeAwards";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string formCollection = "formCollection";
        }
        static readonly ActionParamsClass_BadgeAwards s_params_BadgeAwards = new ActionParamsClass_BadgeAwards();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BadgeAwards BadgeAwardsParams { get { return s_params_BadgeAwards; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BadgeAwards
        {
            public readonly string userName = "userName";
        }
        static readonly ActionParamsClass_UpdateBadgeAwards s_params_UpdateBadgeAwards = new ActionParamsClass_UpdateBadgeAwards();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateBadgeAwards UpdateBadgeAwardsParams { get { return s_params_UpdateBadgeAwards; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateBadgeAwards
        {
            public readonly string badgeAwardEdits = "badgeAwardEdits";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string BadgeAwards = "BadgeAwards";
                public readonly string Index = "Index";
            }
            public readonly string BadgeAwards = "~/Views/PointsReport/BadgeAwards.cshtml";
            public readonly string Index = "~/Views/PointsReport/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PointsReportController : Magenic.BadgeApplication.Controllers.PointsReportController
    {
        public T4MVC_PointsReportController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Web.Mvc.FormCollection formCollection);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Index(System.Web.Mvc.FormCollection formCollection)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formCollection", formCollection);
            IndexOverride(callInfo, formCollection);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void BadgeAwardsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> BadgeAwards(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BadgeAwards);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            BadgeAwardsOverride(callInfo, userName);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        partial void UpdateBadgeAwardsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.IList<Magenic.BadgeApplication.BusinessLogic.PointsReport.BadgeAwardEdit> badgeAwardEdits);

        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> UpdateBadgeAwards(System.Collections.Generic.IList<Magenic.BadgeApplication.BusinessLogic.PointsReport.BadgeAwardEdit> badgeAwardEdits)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateBadgeAwards);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "badgeAwardEdits", badgeAwardEdits);
            UpdateBadgeAwardsOverride(callInfo, badgeAwardEdits);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
