// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4Mvc;
namespace T4Mvc
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AdminNavbar = "_AdminNavbar";
                public readonly string _BadgeWindow = "_BadgeWindow";
                public readonly string _CommunityBadgeTemplate = "_CommunityBadgeTemplate";
                public readonly string _CorporateBadgeTemplate = "_CorporateBadgeTemplate";
                public readonly string _Layout = "_Layout";
                public readonly string _Navbar = "_Navbar";
                public readonly string Error = "Error";
            }
            public readonly string _AdminNavbar = "~/Views/Shared/_AdminNavbar.cshtml";
            public readonly string _BadgeWindow = "~/Views/Shared/_BadgeWindow.cshtml";
            public readonly string _CommunityBadgeTemplate = "~/Views/Shared/_CommunityBadgeTemplate.cshtml";
            public readonly string _CorporateBadgeTemplate = "~/Views/Shared/_CorporateBadgeTemplate.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _Navbar = "~/Views/Shared/_Navbar.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string ApproveActivityBadgeItem = "ApproveActivityBadgeItem";
                public readonly string BadgeItem = "BadgeItem";
                public readonly string EarnedBadgeCollection = "EarnedBadgeCollection";
                public readonly string EarnedBadgeItem = "EarnedBadgeItem";
                public readonly string TotalAccountInfo = "TotalAccountInfo";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string BadgeAwardEdit = "BadgeAwardEdit";
                public readonly string BadgeAwardEditCollection = "BadgeAwardEditCollection";
                public readonly string BadgeEditViewModel = "BadgeEditViewModel";
                public readonly string LogOnViewModel = "LogOnViewModel";
                public readonly string PointsReportCollection = "PointsReportCollection";
                public readonly string SubmitActivity = "SubmitActivity";
                public readonly string SubmitBadgeRequest = "SubmitBadgeRequest";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
