//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenic.BadgeApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magenic.BadgeApplication.Resources.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountHeader {
            get {
                return ResourceManager.GetString("AccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountLink {
            get {
                return ResourceManager.GetString("AccountLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities for Approval.
        /// </summary>
        public static string ActivitiesForApproval {
            get {
                return ResourceManager.GetString("ActivitiesForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities for Approval.
        /// </summary>
        public static string ActivitiesForApprovalHeader {
            get {
                return ResourceManager.GetString("ActivitiesForApprovalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string ActivitiesLink {
            get {
                return ResourceManager.GetString("ActivitiesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These activities are required for this badge:.
        /// </summary>
        public static string ActivitiesRequiredForBadgeLabel {
            get {
                return ResourceManager.GetString("ActivitiesRequiredForBadgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Activities Required.
        /// </summary>
        public static string ActivityPointsAmountLabel {
            get {
                return ResourceManager.GetString("ActivityPointsAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ActivitySubmissionDateLabel {
            get {
                return ResourceManager.GetString("ActivitySubmissionDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Description.
        /// </summary>
        public static string ActivitySubmissionNotesLabel {
            get {
                return ResourceManager.GetString("ActivitySubmissionNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Type.
        /// </summary>
        public static string ActivitySubmissionTypeLabel {
            get {
                return ResourceManager.GetString("ActivitySubmissionTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ActivityTypeLabel {
            get {
                return ResourceManager.GetString("ActivityTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Badge.
        /// </summary>
        public static string AddABadgeButton {
            get {
                return ResourceManager.GetString("AddABadgeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Badge.
        /// </summary>
        public static string AddBadgeHeader {
            get {
                return ResourceManager.GetString("AddBadgeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit Badges.
        /// </summary>
        public static string AddEditBadges {
            get {
                return ResourceManager.GetString("AddEditBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveActivityLink {
            get {
                return ResourceManager.GetString("ApproveActivityLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many times the activity must be completed?.
        /// </summary>
        public static string BadgeActivityCompletedLabel {
            get {
                return ResourceManager.GetString("BadgeActivityCompletedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awarded: .
        /// </summary>
        public static string BadgeAwardedLabel {
            get {
                return ResourceManager.GetString("BadgeAwardedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string BadgeCommunityLabel {
            get {
                return ResourceManager.GetString("BadgeCommunityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string BadgeCorporateLabel {
            get {
                return ResourceManager.GetString("BadgeCorporateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description including why / how it is awarded.
        /// </summary>
        public static string BadgeDescriptionLabel {
            get {
                return ResourceManager.GetString("BadgeDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should it be displayed only once?.
        /// </summary>
        public static string BadgeDisplayOnceLabel {
            get {
                return ResourceManager.GetString("BadgeDisplayOnceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Earned.
        /// </summary>
        public static string BadgeEarnedRowHeader {
            get {
                return ResourceManager.GetString("BadgeEarnedRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here we can create new badges and assign them to an activity..
        /// </summary>
        public static string BadgeEditDescription {
            get {
                return ResourceManager.GetString("BadgeEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string BadgeEndDateLabel {
            get {
                return ResourceManager.GetString("BadgeEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge History.
        /// </summary>
        public static string BadgeHistoryHeader {
            get {
                return ResourceManager.GetString("BadgeHistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge image.
        /// </summary>
        public static string BadgeImageLabel {
            get {
                return ResourceManager.GetString("BadgeImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is management approval required?.
        /// </summary>
        public static string BadgeManagementApprovalRequiredLabel {
            get {
                return ResourceManager.GetString("BadgeManagementApprovalRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Manager.
        /// </summary>
        public static string BadgeManagerLink {
            get {
                return ResourceManager.GetString("BadgeManagerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can it be awarded multiple times?.
        /// </summary>
        public static string BadgeMultipleAwardsLabel {
            get {
                return ResourceManager.GetString("BadgeMultipleAwardsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge name.
        /// </summary>
        public static string BadgeNameLabel {
            get {
                return ResourceManager.GetString("BadgeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points received.
        /// </summary>
        public static string BadgePointsReceievedLabel {
            get {
                return ResourceManager.GetString("BadgePointsReceievedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string BadgePriorityLabel {
            get {
                return ResourceManager.GetString("BadgePriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string BadgesLink {
            get {
                return ResourceManager.GetString("BadgesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string BadgeStartDateLabel {
            get {
                return ResourceManager.GetString("BadgeStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quip or funny saying about the badge.
        /// </summary>
        public static string BadgeTaglineLabel {
            get {
                return ResourceManager.GetString("BadgeTaglineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click this image and save it to your desktop to use as a badge template..
        /// </summary>
        public static string BadgeTemplateText {
            get {
                return ResourceManager.GetString("BadgeTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements for the {0} badge.
        /// </summary>
        public static string BadgeTitle {
            get {
                return ResourceManager.GetString("BadgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Type.
        /// </summary>
        public static string BadgeTypeLabel {
            get {
                return ResourceManager.GetString("BadgeTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Type.
        /// </summary>
        public static string BadgeTypeRowHeader {
            get {
                return ResourceManager.GetString("BadgeTypeRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Information.
        /// </summary>
        public static string BadgeWindowTitle {
            get {
                return ResourceManager.GetString("BadgeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Badges.
        /// </summary>
        public static string CommunityBadgeHeader {
            get {
                return ResourceManager.GetString("CommunityBadgeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Badges for Approval.
        /// </summary>
        public static string CommunityBadgesForApproval {
            get {
                return ResourceManager.GetString("CommunityBadgesForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Badges for Approval.
        /// </summary>
        public static string CommunityBadgesForApprovalHeader {
            get {
                return ResourceManager.GetString("CommunityBadgesForApprovalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Badge Template.
        /// </summary>
        public static string CommunityBadgeTemplate {
            get {
                return ResourceManager.GetString("CommunityBadgeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string CompareLink {
            get {
                return ResourceManager.GetString("CompareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Payout of Selected User(s).
        /// </summary>
        public static string ConfirmPayoutSelectedUsers {
            get {
                return ResourceManager.GetString("ConfirmPayoutSelectedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Badges.
        /// </summary>
        public static string CorporateBadgeHeader {
            get {
                return ResourceManager.GetString("CorporateBadgeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Badge Template.
        /// </summary>
        public static string CorporateBadgeTemplate {
            get {
                return ResourceManager.GetString("CorporateBadgeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Earned.
        /// </summary>
        public static string DateEarnedRowHeader {
            get {
                return ResourceManager.GetString("DateEarnedRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earned community badge(s).
        /// </summary>
        public static string EarnedCommunityBadgesLabel {
            get {
                return ResourceManager.GetString("EarnedCommunityBadgesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earned corporate badge(s).
        /// </summary>
        public static string EarnedCorporateBadgesLabel {
            get {
                return ResourceManager.GetString("EarnedCorporateBadgesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a Badge.
        /// </summary>
        public static string EditBadgeHeader {
            get {
                return ResourceManager.GetString("EditBadgeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payout Threshold.
        /// </summary>
        public static string InvalidPayoutThreshold {
            get {
                return ResourceManager.GetString("InvalidPayoutThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LeaderboardHeader {
            get {
                return ResourceManager.GetString("LeaderboardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LeaderboardLink {
            get {
                return ResourceManager.GetString("LeaderboardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard Ranking.
        /// </summary>
        public static string LeaderboardRankingHeader {
            get {
                return ResourceManager.GetString("LeaderboardRankingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOffLink {
            get {
                return ResourceManager.GetString("LogOffLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenic Badge Application Logo.
        /// </summary>
        public static string LogoTitle {
            get {
                return ResourceManager.GetString("LogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Activities.
        /// </summary>
        public static string ManageActivitiesHeader {
            get {
                return ResourceManager.GetString("ManageActivitiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Activities.
        /// </summary>
        public static string ManageActivitiesLink {
            get {
                return ResourceManager.GetString("ManageActivitiesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Out.
        /// </summary>
        public static string PaidOutRowHeader {
            get {
                return ResourceManager.GetString("PaidOutRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Payout Threshold.
        /// </summary>
        public static string PointPayoutThresholdHeader {
            get {
                return ResourceManager.GetString("PointPayoutThresholdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Awarded.
        /// </summary>
        public static string PointsAwardedRowHeader {
            get {
                return ResourceManager.GetString("PointsAwardedRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Earned:.
        /// </summary>
        public static string PointsEarnedLabel {
            get {
                return ResourceManager.GetString("PointsEarnedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Report.
        /// </summary>
        public static string PointsReport {
            get {
                return ResourceManager.GetString("PointsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current points for a user are calculated by summing the points values for all User Badge records that are marked as not being paid out..
        /// </summary>
        public static string PointsReportDescription {
            get {
                return ResourceManager.GetString("PointsReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Report.
        /// </summary>
        public static string PointsReportHeader {
            get {
                return ResourceManager.GetString("PointsReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PointsReportNameHeader {
            get {
                return ResourceManager.GetString("PointsReportNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Total.
        /// </summary>
        public static string PointsReportPointsTotalHeader {
            get {
                return ResourceManager.GetString("PointsReportPointsTotalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Activities.
        /// </summary>
        public static string PreviousActivitiesHeader {
            get {
                return ResourceManager.GetString("PreviousActivitiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileLink {
            get {
                return ResourceManager.GetString("ProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string RankTableBadgesHeader {
            get {
                return ResourceManager.GetString("RankTableBadgesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string RankTableCompleteHeader {
            get {
                return ResourceManager.GetString("RankTableCompleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string RankTableIdHeader {
            get {
                return ResourceManager.GetString("RankTableIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RankTableNameHeader {
            get {
                return ResourceManager.GetString("RankTableNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectActivityLink {
            get {
                return ResourceManager.GetString("RejectActivityLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Required Activities.
        /// </summary>
        public static string RequiredActivitiesLabel {
            get {
                return ResourceManager.GetString("RequiredActivitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResultsHeader {
            get {
                return ResourceManager.GetString("SearchResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTextLabel {
            get {
                return ResourceManager.GetString("SearchTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ShowAllCommunityBadges {
            get {
                return ResourceManager.GetString("ShowAllCommunityBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ShowAllCorporateBadges {
            get {
                return ResourceManager.GetString("ShowAllCorporateBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned.
        /// </summary>
        public static string ShowEarnedCommunityBadges {
            get {
                return ResourceManager.GetString("ShowEarnedCommunityBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned.
        /// </summary>
        public static string ShowEarnedCorporateBadges {
            get {
                return ResourceManager.GetString("ShowEarnedCorporateBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a Completed Activity.
        /// </summary>
        public static string SubmitCompletedActivityHeader {
            get {
                return ResourceManager.GetString("SubmitCompletedActivityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve unlocked the {0} award!.
        /// </summary>
        public static string UnlockedAwardTitle {
            get {
                return ResourceManager.GetString("UnlockedAwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserIdLabel {
            get {
                return ResourceManager.GetString("UserIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
    }
}
